// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    NEXT_PUBLIC_BASE_URL: string;
    DB1: D1Database
    DB2: D1Database
    OPENAI_API_KEY: string;
}
